
services:
#  app:
#    build: .
#    ports:
#      - "3000:3000"
#    environment:
#      - WORKER_CONCURRENCY=6
#      - MONGO_URI=mongodb://mongo:27017/telnet_audit
#    depends_on:
#      - redis
#      - mongo
  redis:
    image: redis
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    ports:
      - "27017:27017"

#  rabbitmq:
#    image: rabbitmq:3-management
#    ports:
#      - "5672:5672"
#      - "15672:15672"
